[project]
name = "cfd8"
version = "0.1.0"
description = "MSc CFD Individual dissertation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib",
    "numpy",
    "pyqt5",
    "pyvista",
]
